---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .git/
  .venv/
  __pycache__/
  build/
  dist/
  rpmbuild/
  debbuild/
  *.lock
  Pipfile.lock





