---
name: dfakeseeder
version: '1.0.15'
summary: BitTorrent seeding simulator for testing and development
icon: d_fake_seeder/components/images/dfakeseeder.png
description: |
  D' Fake Seeder is a sophisticated Python GTK4 BitTorrent client that
  simulates seeding activity with advanced peer-to-peer networking
  capabilities.

  Core Features:
    - Multi-torrent support with individual configuration per torrent
    - Full HTTP and UDP tracker compatibility (BEP-003)
    - Advanced peer-to-peer networking with incoming/outgoing connections
    - Real-time connection tracking and performance metrics
    - UPnP port forwarding for NAT traversal
    - Protocol encryption (MSE/PE) support

  User Interface:
    - Modern GTK4 + LibAdwaita UI with responsive design
    - System tray integration with D-Bus IPC
    - Multi-tab settings (General, Connection, Peer Protocol, Advanced)
    - Speed control toolbar for upload and download limits
    - Real-time torrent status and peer monitoring

  Internationalization:
    - 21 languages supported including English, Spanish, French, German,
      Italian, Portuguese, Russian, Chinese, Japanese, Korean, Arabic,
      Hindi, Dutch, Swedish, Polish, Irish, and more
    - Runtime language switching without restart

  Desktop Integration:
    - XDG-compliant configuration and data paths
    - Desktop file and icon theme integration
    - GNOME Shell support
    - Application menu integration

  Web UI:
    - Built-in web interface for remote monitoring
    - Accessible from any browser on the local network

  Developer and Testing:
    - 140+ automated E2E tests across RPM, DEB, and PyPI
    - Available as DEB, RPM, PyPI, Docker, Flatpak, and Snap packages
    - Comprehensive CI/CD pipeline with GitHub Actions
base: core24
grade: stable
confinement: strict

apps:
  dfakeseeder:
    command: bin/dfakeseeder
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media
    desktop: share/applications/ie.fio.dfakeseeder.desktop

  dfs:
    command: bin/dfs
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media

  dfs-tray:
    command: bin/dfs-tray
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  dfakeseeder:
    plugin: python
    source: .
    python-packages:
      - requests>=2.31.0
      - typer>=0.12.3
      - urllib3>=1.26.18
      - watchdog>=4.0.0
      - bencodepy>=0.9.5
      - aiohttp>=3.8.0
      - aiohttp-session>=2.12.0
      - pycryptodome>=3.15.0
      - psutil>=5.9.0
    build-packages:
      - python3-dev
      - libcairo2-dev
      - pkg-config
      - libminiupnpc-dev
    stage-packages:
      - gir1.2-gtk-4.0
      - libadwaita-1-0
      - gir1.2-adw-1
      - python3-gi
      - python3-gi-cairo
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - gtk-update-icon-cache
      - desktop-file-utils
      - libminiupnpc17
    override-build: |
      craftctl default
      install -Dm644 ${CRAFT_PART_SRC}/d_fake_seeder/components/images/dfakeseeder.png \
        ${CRAFT_PART_INSTALL}/share/icons/hicolor/256x256/apps/ie.fio.dfakeseeder.png
      install -Dm644 ${CRAFT_PART_SRC}/ie.fio.dfakeseeder.desktop \
        ${CRAFT_PART_INSTALL}/share/applications/ie.fio.dfakeseeder.desktop
      install -Dm644 ${CRAFT_PART_SRC}/ie.fio.dfakeseeder.metainfo.xml \
        ${CRAFT_PART_INSTALL}/share/metainfo/ie.fio.dfakeseeder.metainfo.xml
