name: dfakeseeder
version: '1.0.11'
summary: BitTorrent seeding simulator for testing and development
description: |
  D' Fake Seeder is a Python GTK4 BitTorrent client that simulates seeding
  activity with advanced peer-to-peer networking capabilities. Features include
  multi-language support (21 languages), system tray integration, web UI,
  UPnP port forwarding, and protocol encryption (MSE/PE).
base: core22
grade: stable
confinement: strict

apps:
  dfakeseeder:
    command: bin/dfakeseeder
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media
    desktop: share/applications/ie.fio.dfakeseeder.desktop

  dfs:
    command: bin/dfs
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media

  dfs-tray:
    command: bin/dfs-tray
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  dfakeseeder:
    plugin: python
    source: .
    python-packages:
      - requests>=2.31.0
      - typer>=0.12.3
      - urllib3>=1.26.18
      - PyGObject>=3.42.0
      - watchdog>=4.0.0
      - bencodepy>=0.9.5
      - aiohttp>=3.8.0
      - aiohttp-session>=2.12.0
      - miniupnpc>=2.2.0
      - pycryptodome>=3.15.0
      - psutil>=5.9.0
    build-packages:
      - python3-dev
      - libcairo2-dev
      - libgirepository1.0-dev
      - pkg-config
      - miniupnpc
    stage-packages:
      - gir1.2-gtk-4.0
      - libadwaita-1-0
      - gir1.2-adw-1
      - python3-gi
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - gtk-update-icon-cache
      - desktop-file-utils
      - libminiupnpc-dev
    override-build: |
      craftctl default
      install -Dm644 ${CRAFT_PART_SRC}/d_fake_seeder/components/images/dfakeseeder.png \
        ${CRAFT_PART_INSTALL}/share/icons/hicolor/256x256/apps/ie.fio.dfakeseeder.png
      install -Dm644 ${CRAFT_PART_SRC}/ie.fio.dfakeseeder.desktop \
        ${CRAFT_PART_INSTALL}/share/applications/ie.fio.dfakeseeder.desktop
      install -Dm644 ${CRAFT_PART_SRC}/ie.fio.dfakeseeder.metainfo.xml \
        ${CRAFT_PART_INSTALL}/share/metainfo/ie.fio.dfakeseeder.metainfo.xml
