---
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [ refresh ]
    
permissions: write-all

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      pypi-extension: "true"
      deb-build: "true"
      rpm-build: "true"
      snap-build: "true"
      docker-build: "true"
      aur-publish: "true"
